# Generated by Django 2.2.6 on 2019-11-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecord',
            old_name='daye',
            new_name='date',
        ),
    ]
